labels: [fix, chore, ui]
labelMapping:
  feat: [feature]
  fix(ui): [fix, ui]
  feat(ui): [feat, ui]
  refactor: [chore, refactor]
  chore(refactor): [chore, refactor]
  chore(deps): [dependencies]
  chore(docs): [chore, docs]
  docs: [chore, docs]
  test: [chore, test]
  chore(ci): [chore, tools, ci]
  chore(tools): [chore, tools]
  chore(release): [chore, release]